name: CICD Staging

on:
  push:
    branches:
      - stg

env:
  NOCODB_API_TOKEN: ${{ secrets.STG_NOCODB_API_TOKEN }}
  NOCODB_API_URL: ${{ secrets.STG_NOCODB_API_URL }}
  NOCODB_COMPANY_DB: ${{ secrets.STG_NOCODB_COMPANY_DB }}
  NOCODB_SEMINAR_DB: ${{ secrets.STG_NOCODB_SEMINAR_DB }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GTK_STG }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/ce-smart-career/${{ github.event.repository.name }}-stg:latest
          secrets: |
            NOCODB_API_TOKEN=${{ secrets.STG_NOCODB_API_TOKEN }}
            NOCODB_API_URL=${{ secrets.STG_NOCODB_API_URL }}
            NOCODB_COMPANY_DB=${{ secrets.STG_NOCODB_COMPANY_DB }}
            NOCODB_SEMINAR_DB=${{ secrets.STG_NOCODB_SEMINAR_DB }}

  deploy:
    name: deploy
    needs: ['build']
    runs-on: [self-hosted, runner-stg]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GTK_STG }}

      - name: Deploy docker-compose stack
        run: docker compose up -d --build --force-recreate

      - name: Prune Docker system
        run: docker system prune -af
